name: Auto Merge Owner PR
on:
  pull_request:
    types: [opened, reopened]
jobs:
  # May consider adding a job that does the initial checking or linting before merge
  merge:
    if: github.actor == 'arpitparasana'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: managedkaos/merge-pull-request@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
