name: Hello World
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - run: echo Hello, world!
        - run: date
  print-env:
    runs-on: ubuntu-latest
    steps:
        - run: env | sort
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: adopt
          
