name: Hello World
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
        - run: echo Hello, world!
        - run: date
  print-env:
    runs-on: ubuntu-latest
    steps:
        - run: env | sort
